apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-samples
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
    - namespace: "app-sample"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elixirdemo
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      #name: '{{cluster}}-elixirdemo'
      name: elixirdemo
    spec:
      project: app-samples
      source:
        repoURL: https://github.com/SnowBiz/elixirdemo.git
        targetRevision: HEAD
        path: kubernetes/helm
        helm: 
          valueFiles:
           #- values-{{cluster}}-elixirdemo.yaml
      destination:
        server: '{{url}}'
        namespace: app-sample
        