apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app
  namespace: argocd
spec:
  project: default
  source:
    path: apps/
    repoURL: https://github.com/snowbiz/gitops.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    namespace: 'argocd'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
